import { chat, interviewerConfig, type ChatMessage } from "@cr/llm";
import { extractJson } from "./interview.js";

/**
 * Idea suggestions for the Home screen. Returns one "gold" headline idea plus two
 * "silver" alternatives, each a short title + one-line pitch. Generated by the
 * interviewer model with a JSON contract; falls back to a static set if the model
 * is unconfigured or misbehaves so the UI always has something to show.
 */

export interface Idea {
  title: string;
  pitch: string;
}

export interface IdeaSet {
  gold: Idea;
  silver: [Idea, Idea];
}

export type SuggestMode = "initial" | "random" | "similar";

export interface SuggestInput {
  seed?: string;
  mode: SuggestMode;
  basedOn?: { title: string; pitch: string };
}

const FALLBACK: IdeaSet = {
  gold: {
    title: "Plant Care Buddy",
    pitch: "Never let a plant die again — gentle reminders for watering day.",
  },
  silver: [
    { title: "Meal Planner", pitch: "Plan the week's dinners and get the grocery list made for you." },
    { title: "Money Saver", pitch: "Watch your spending and hit savings goals without the stress." },
  ],
};

function prompt(input: SuggestInput): ChatMessage[] {
  const sys: ChatMessage = {
    role: "system",
    content: `You suggest mobile app ideas for a no-code app builder used by everyday people who
have never made an app. Make every idea feel personal, doable, and exciting to a non-technical person.
Reply with ONLY a JSON object (no markdown) of the shape:
{"gold": {"title": string, "pitch": string},
 "silver": [{"title": string, "pitch": string}, {"title": string, "pitch": string}]}
RULES:
- Titles are 2-4 plain words (no jargon, no "app" in the title).
- Pitches name a REAL everyday benefit the person feels, in their words, under 80 characters.
  Good: "Never forget to water your plants again." Bad: "A utility for plant care management."
- "gold" is the most delightful, most relatable idea; "silver" are two solid alternatives.`,
  };

  let user: string;
  if (input.mode === "similar" && input.basedOn) {
    user = `Suggest ideas similar to "${input.basedOn.title}" (${input.basedOn.pitch}). Keep the same spirit but offer fresh angles.`;
  } else if (input.mode === "initial" && input.seed?.trim()) {
    user = `The person is interested in: "${input.seed.trim()}". Suggest app ideas that fit their life.`;
  } else {
    user = `Suggest three diverse, delightful app ideas a regular person would love to make for their own life.`;
  }
  return [sys, { role: "user", content: user }];
}

function valid(set: any): set is IdeaSet {
  return (
    set &&
    set.gold?.title &&
    set.gold?.pitch &&
    Array.isArray(set.silver) &&
    set.silver.length >= 2 &&
    set.silver[0]?.title &&
    set.silver[1]?.title
  );
}

export async function suggestIdeas(input: SuggestInput): Promise<IdeaSet> {
  try {
    const raw = await chat(interviewerConfig(), {
      messages: prompt(input),
      temperature: 0.9,
      maxTokens: 500,
    });
    const parsed = extractJson<IdeaSet>(raw);
    if (valid(parsed)) {
      return { gold: parsed.gold, silver: [parsed.silver[0], parsed.silver[1]] };
    }
  } catch {
    /* fall through to fallback */
  }
  return FALLBACK;
}
