import { chat, interviewerConfig, type ChatMessage } from "@cr/llm";
import { extractJson } from "./interview.js";

/**
 * Idea suggestions for the Home screen. Returns one "gold" headline idea plus two
 * "silver" alternatives, each a short title + one-line pitch. Generated by the
 * interviewer model with a JSON contract; falls back to a static set if the model
 * is unconfigured or misbehaves so the UI always has something to show.
 */

export interface Idea {
  title: string;
  pitch: string;
}

export interface IdeaSet {
  gold: Idea;
  silver: [Idea, Idea];
}

export type SuggestMode = "initial" | "random" | "similar";

export interface SuggestInput {
  seed?: string;
  mode: SuggestMode;
  basedOn?: { title: string; pitch: string };
}

const FALLBACK: IdeaSet = {
  gold: {
    title: "Streak Coach",
    pitch: "Turns daily wins into streaks people keep coming back for.",
  },
  silver: [
    { title: "Booked Up", pitch: "Lets local businesses take bookings their clients love." },
    { title: "Stash Quest", pitch: "Makes saving money a game people actually want to play." },
  ],
};

function prompt(input: SuggestInput): ChatMessage[] {
  const sys: ChatMessage = {
    role: "system",
    content: `You suggest mobile app ideas for a no-code builder. The user is a first-time creator who
wants to BUILD AND PUBLISH an app that OTHER people will download and use — not a private tool just for
themselves. So every idea is a real little product with an audience, but described warmly and simply,
so a non-technical creator instantly thinks "I could make that, and people would love it."
Reply with ONLY a JSON object (no markdown) of the shape:
{"gold": {"title": string, "pitch": string},
 "silver": [{"title": string, "pitch": string}, {"title": string, "pitch": string}]}
RULES:
- Titles are 2-4 plain words (no jargon, no "app" in the title).
- Pitches name a REAL benefit the app's USERS feel, warm and human, under 80 characters.
  Good: "Turns daily wins into streaks people keep coming back for."
  Bad (too personal/just-for-me): "Helps me remember to water my plants."
  Bad (too corporate): "A utility for habit management and retention."
- Frame it for an audience ("people", "users", "fans", "locals", "families") — but keep one relatable
  human spark, never a pitch-deck tone.
- "gold" is the most delightful, broadly-appealing idea; "silver" are two solid alternatives.`,
  };

  let user: string;
  if (input.mode === "similar" && input.basedOn) {
    user = `Suggest ideas similar to "${input.basedOn.title}" (${input.basedOn.pitch}). Keep the same spirit but offer fresh angles.`;
  } else if (input.mode === "initial" && input.seed?.trim()) {
    user = `The creator is interested in: "${input.seed.trim()}". Suggest apps about this that real people would download and use.`;
  } else {
    user = `Suggest three diverse, delightful apps a first-time creator could publish that real people would love to use.`;
  }
  return [sys, { role: "user", content: user }];
}

function valid(set: any): set is IdeaSet {
  return (
    set &&
    set.gold?.title &&
    set.gold?.pitch &&
    Array.isArray(set.silver) &&
    set.silver.length >= 2 &&
    set.silver[0]?.title &&
    set.silver[1]?.title
  );
}

export async function suggestIdeas(input: SuggestInput): Promise<IdeaSet> {
  try {
    const raw = await chat(interviewerConfig(), {
      messages: prompt(input),
      temperature: 0.9,
      maxTokens: 500,
    });
    const parsed = extractJson<IdeaSet>(raw);
    if (valid(parsed)) {
      return { gold: parsed.gold, silver: [parsed.silver[0], parsed.silver[1]] };
    }
  } catch {
    /* fall through to fallback */
  }
  return FALLBACK;
}
